version: '3.8'

services:
  # SQL Server service
  traderdirectdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "5434:1433"  # Exposes SQL Server to the host on port 5434
    environment:
      SA_PASSWORD: "root@123"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    volumes:
      - trader_direct_db_data:/var/opt/sqlserver/data
    networks:
      - trader_direct_network

  traderdirectapp:
    build:
      context: .
      dockerfile: TraderDirect.App/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=traderdirectdb;Database=TraderDirectDb;User Id=sa;Password=root@123;TrustServerCertificate=True;"
      RabbitMq__ConnectionString: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - traderdirectdb
      - rabbitmq
    networks:
      - trader_direct_network

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - trader_direct_network

  tradesmessageconsumer:
    build:
      context: .
      dockerfile: TradesMessageConsumer/Dockerfile
    environment:
      RabbitMq__ConnectionString: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - rabbitmq 
    networks:
      - trader_direct_network

volumes:
  trader_direct_db_data:
    driver: local

networks:
  trader_direct_network:
    driver: bridge
